CREATE TABLE `assignments` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `surveyPeriodId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `mode` json DEFAULT NULL,
  `assignmentErrorStatusType` int DEFAULT NULL,
  `userIdResponsibility` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `approvedByCreator` tinyint(1) DEFAULT NULL,
  `codeIdentity` text,
  `assignmentStatusId` int DEFAULT NULL,
  `assignmentStatusAlias` varchar(255) DEFAULT NULL,
  `data1` varchar(255) DEFAULT NULL,
  `data2` varchar(255) DEFAULT NULL,
  `data3` varchar(255) DEFAULT NULL,
  `data4` varchar(255) DEFAULT NULL,
  `data5` varchar(255) DEFAULT NULL,
  `data6` varchar(255) DEFAULT NULL,
  `data7` varchar(255) DEFAULT NULL,
  `data8` varchar(255) DEFAULT NULL,
  `data9` varchar(255) DEFAULT NULL,
  `data10` varchar(255) DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `dateModified` datetime DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `done` tinyint(1) DEFAULT NULL,
  `secondary` tinyint(1) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `copyFromId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `externalDone` tinyint(1) DEFAULT NULL,
  `currentUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `currentUserUsername` varchar(255) DEFAULT NULL,
  `currentUserFullname` varchar(255) DEFAULT NULL,
  `currentUserSurveyRoleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `currentUserSurveyRoleName` varchar(255) DEFAULT NULL,
  `currentUserSurveyRoleIsPencacah` tinyint(1) DEFAULT NULL,
  `currentUserSurveyRoleCanPullSample` tinyint(1) DEFAULT NULL,
  `sourceFrom` varchar(255) DEFAULT NULL,
  `listing` tinyint(1) DEFAULT NULL,
  `assignmentResponsibility` json DEFAULT NULL,
  `assignmentResponsibilityAdmin` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `regionMetadata` json DEFAULT NULL,
  `sampleType` int DEFAULT NULL,
  `isTarget` tinyint(1) DEFAULT NULL,
  `referencedTo` json DEFAULT NULL,
  `lockedByUser` tinyint(1) DEFAULT NULL,
  `lockedByAnother` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


ALTER TABLE `assignments`
  ADD PRIMARY KEY (`id`);